export default function Projects() {
  const projects = [
    {
      id: 1,
      title: "Did I Yap?",
      description: "A machine learning-based approach to identifying hallucinated (factually incorrect or fabricated) outputs generated by large-scale language models. The project emphasizes the need for factual reliability in AI-generated text and provides a pipeline to classify outputs using traditional and ensemble-based classifiers.",
      tags: ["GCP", "Docker", "BERT", "Jinja", "HTML/CSS", "Boosting"],
      github: "https://github.com/Karthikeyanswami/Hallucination-Detection-in-LLMs"
    },
    {
      id: 2,
      title: "InternAway",
      description: "A full-stack web application that simplifies the management of student internships. Enables students to upload and manage internship documents while allowing coordinators to verify details and maintain centralized records efficiently.",
      tags: ["React.js", "Node.js", "MongoDB", "JWT", "Express.js", "Google Drive API"],
      github: "https://github.com/LaviVasudevan/Internaway"
    },
    {
      id: 3,
      title: "Stratego",
      description: "A Python-based simulation of the classic board game Stratego with a simplified 8x8 board and 16 pieces per player. Incorporates AI elements using genetic algorithms for AI setup and rule-based heuristics for decision-making during gameplay. (My favourite yet!)",
      tags: ["Python", "Genetic Algorithms", "Heuristics", "AI Agents", "Decision Making"],
      github: "https://github.com/LaviVasudevan/STRATEGO-SIMPLIFIED"
    },
    {
      id: 4,
      title: "AuraPharm",
      description: "Pharmacy Supply Chain Management System designed to streamline interactions between manufacturers, wholesalers, pharmacies, and waste management agencies. Optimizes medicine production, distribution, and waste collection for efficient supply chain management.",
      tags: ["NetBeans", "Oracle SQL", "PL/SQL", "Java", "VSCode"],
      github: "https://github.com/LaviVasudevan/Pharma-Supply-Chain-Management-System"
    },
    {
      id: 5,
      title: "SectorComply",
      description: "Sector Comply is a sector-specific compliance and financial insights platform that integrates regulatory tracking, budget analysis, and AI-powered Q&A. Tailored for professionals, enterprises, and policymakers, it helps users stay updated with industry-specific regulations and financial trends.",
      tags: ["Flutter", "Dart", "Firebase", "REST APIs", "Flask", "Android Studio"],
      github: "https://github.com/LaviVasudevan/SectorComply"
    },
    {
      id: 6,
      title: "Pay Equity",
      description: "The Pay Equity Analysis Tool is a software designed to analyze payroll data sets spanning five years for any company, including the current year. It provides insightful visualizations and statistical analysis to help companies understand, make informed decisions and address pay disparities within the organization.",
      tags: ["Python", "Gradio", "Plotly API", "OneAPI", "Git"],
      github: "https://github.com/VidishaDesai/OneAPI-INTEL-lectuals"
    }
  ]

  return (
    <section id="projects" className="section bg-gray-800/50">
      <div className="container">
        <h2 className="section-title text-gradient">
          Projects
        </h2>
        
        {/* All Projects as Featured */}
        <div className="grid md:grid-cols-2 gap-8">
          {projects.map((project) => (
            <div key={project.id} className="card group hover:scale-105 transform transition-all duration-300">
              <div className="relative overflow-hidden rounded-lg mb-4">
                <div className="w-full h-48 bg-gradient-to-br from-blue-500/20 to-purple-500/20 flex items-center justify-center">
                  <span className="text-4xl opacity-50">👾</span>
                </div>
                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                  <div className="flex space-x-4">
                    <a
                      href={project.github}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="bg-white/20 hover:bg-white/30 p-2 rounded-full transition-colors"
                    >
                      <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"/>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              
              <h3 className="text-xl font-bold mb-2">{project.title}</h3>
              <p className="text-gray-400 mb-4">{project.description}</p>
              
              <div className="flex flex-wrap gap-2">
                {project.tags.map((tag) => (
                  <span key={tag} className="bg-blue-500/20 text-blue-400 px-2 py-1 rounded text-sm">
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}